services:
  mysql:
    image: mysql:8.0.29
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reversi
      MYSQL_USER: reversi
      MYSQL_PASSWORD: password
